export { default as ChevronIcon } from "./chevron.tsx";
export { default as ArrowIcon } from "./arrow";
export { default as CalenderIcon } from "./calendar";
// export { default as CaretIcon } from "./caret";
export { default as FacebookIcon } from "./facebook";
export { default as FreeIcon } from "./freeIcon";
export { default as InstagramIcon } from "./instagram";
export { default as LinkedInIcon } from "./linkedIn";
export { default as LocationIcon } from "./location";
export { default as NextIcon } from "./next";
export { default as reviousIcon } from "./previous";
export { default as TwitterIcon } from "./twitter";
